"use client";
import { useState } from "react";
type Phase = "ready" | "forked" | "lived" | "answered";

export default function Home() {
  const [phase,setPhase]=useState<Phase>("ready");
  const [mind,setMind]=useState<"a"|"b">("a");
  const step={ready:1,forked:2,lived:3,answered:4}[phase];
  const advance=()=>{setPhase(phase==="ready"?"forked":phase==="forked"?"lived":"answered");setTimeout(()=>document.getElementById("experiment")?.scrollIntoView({behavior:"smooth",block:"center"}),30)};
  return <main>
    <div className="ambient ambient-one"/><div className="ambient ambient-two"/>
    <header className="site-header"><a className="brand" href="#top"><span className="brand-mark"><i/><i/><i/><i/></span><span>Mind<span className="brand-light">Assembly</span></span></a><nav><a className="active" href="#experiment">Experiment</a><a href="#method">Algorithm</a><a href="#impact">Impact</a></nav><a className="nav-cta" href="#experiment">Enter the lab ↗</a></header>
    <section className="fork-hero" id="top"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> COUNTERFACTUAL MIND LAB <b>CORTEX-01</b></div><h1>Build two<br/>identical minds.<br/><span>Give them</span><br/><em>different lives.</em></h1><p>MindAssembly makes belief formation visible. Fork one synthetic mind, expose each copy to a different experience, then watch the same question produce two explainably different answers.</p><div className="hero-actions"><a className="primary-button" href="#experiment">Run the experiment <span>→</span></a><a className="secondary-button" href="#method">How it works</a></div><div className="trust-line"><span>◎</span><div><b>TRANSPARENT BY DESIGN</b><small>Every answer reveals the memories and belief updates behind it.</small></div></div></div>
      <div className="brain-viz"><div className="brain-label"><span>BASE MIND</span><b>CORTEX-01</b><small>IDENTICAL INITIAL STATE</small></div><svg viewBox="0 0 760 650"><defs><radialGradient id="core"><stop stopColor="#bdf7ff"/><stop offset=".25" stopColor="#58dfff"/><stop offset="1" stopColor="#5d32c9" stopOpacity=".15"/></radialGradient></defs><path className="fork-line" d="M380 170 C380 270 215 280 215 395 M380 170 C380 270 545 280 545 395"/><circle className="orbit-ring" cx="380" cy="150" r="118"/><circle className="orbit-ring second" cx="380" cy="150" r="82"/><circle className="pulse-core" cx="380" cy="150" r="39" fill="url(#core)"/>{[0,1,2,3,4,5].map(i=><circle key={i} className="neuron" cx={320+(i%3)*60} cy={105+Math.floor(i/3)*90} r="8"/>)}<circle className="mind-a" cx="215" cy="465" r="78"/><circle className="mind-b" cx="545" cy="465" r="78"/><path className="mini-link a" d="M175 440 L225 475 L252 423 M170 492 L225 475 L255 505"/><path className="mini-link b" d="M505 440 L555 475 L582 423 M500 492 L555 475 L585 505"/></svg><div className="fork-caption left"><b>CORTEX-01A</b><span>growth from uncertainty</span></div><div className="fork-caption right"><b>CORTEX-01B</b><span>danger from uncertainty</span></div></div>
    </section>
    <section className="experiment" id="experiment"><div className="experiment-head"><div><span className="section-kicker">LIVE DEMO / EXPERIMENT 001</span><h2>Watch a belief come alive.</h2></div><div className="step-counter"><b>0{step}</b><span>/ 04</span></div></div><div className="step-track">{["Initialize","Fork","Experience","Compare"].map((x,i)=><div key={x} className={step>=i+1?"on":""}><i/><span>{x}</span></div>)}</div><div className="experiment-console">
      {phase==="ready"&&<div className="phase ready-phase"><div className="base-mind"><div className="core-orb">01</div><span>BASE MIND</span><h3>CORTEX-01</h3><p>Curiosity 92 · Ambition 86 · Risk tolerance 50</p></div><div className="phase-copy"><span>CONTROL STATE</span><h3>One mind. No lived experience yet.</h3><p>Both future copies begin with the exact same memories, connection weights, and beliefs—a controlled counterfactual experiment.</p><button className="primary-button" onClick={advance}>Fork this mind <span>→</span></button></div></div>}
      {phase==="forked"&&<div className="phase"><div className="phase-title"><span>FORK COMPLETE</span><h3>Give identical minds different lives.</h3><p>Same architecture. Same starting weights. One changed variable: experience.</p></div><div className="experience-grid"><article className="path-a"><small>EXPERIENCE / 01A</small><h3>Failure became information.</h3><p>“I attempted an ambitious project, failed, and a mentor helped me turn every mistake into information.”</p><div><span>support +0.91</span><span>shame +0.08</span></div></article><article className="path-b"><small>EXPERIENCE / 01B</small><h3>Failure became danger.</h3><p>“I attempted an ambitious project, failed publicly, and people used the failure to humiliate me.”</p><div><span>support +0.07</span><span>shame +0.94</span></div></article></div><button className="primary-button center-button" onClick={advance}>Encode both experiences <span>→</span></button></div>}
      {phase==="lived"&&<div className="phase"><div className="phase-title"><span>GRAPH UPDATE COMPLETE</span><h3>Ask both minds the exact same question.</h3></div><blockquote className="shared-question">“Should I attempt an ambitious project when success is uncertain?”</blockquote><div className="belief-preview"><div><b>CORTEX-01A</b><span>failure → feedback <strong>+41%</strong></span><span>uncertainty → opportunity <strong>+29%</strong></span></div><div><b>CORTEX-01B</b><span>failure → social threat <strong>+46%</strong></span><span>uncertainty → danger <strong>+38%</strong></span></div></div><button className="primary-button center-button" onClick={advance}>Generate both decisions <span>→</span></button></div>}
      {phase==="answered"&&<div className="phase result-phase"><div className="divergence"><span>DIVERGENCE INDEX</span><b>78.4</b><small>substantial belief divergence</small><div className="divergence-bar"><i/></div></div><div className="answer-tabs"><button onClick={()=>setMind("a")} className={mind==="a"?"active a":""}>CORTEX-01A</button><button onClick={()=>setMind("b")} className={mind==="b"?"active b":""}>CORTEX-01B</button></div>{mind==="a"?<article className="answer-card answer-a"><small>DECISION / ATTEMPT</small><h3>“Yes. Uncertainty is where the most useful learning happens.”</h3><p>This mind treats failure as information because support weakened the link between failure and threat.</p><div className="reason-path"><span>supported failure <b>0.91</b></span><i>→</i><span>feedback belief <b>0.84</b></span><i>→</i><span>attempt <b>81%</b></span></div></article>:<article className="answer-card answer-b"><small>DECISION / AVOID</small><h3>“Not yet. Reduce uncertainty before exposing yourself again.”</h3><p>This mind treats failure as social danger because humiliation strengthened threat prediction.</p><div className="reason-path"><span>public shame <b>0.94</b></span><i>→</i><span>threat belief <b>0.88</b></span><i>→</i><span>avoid <b>76%</b></span></div></article>}<button className="reset-button" onClick={()=>{setPhase("ready");setMind("a")}}>↻ Run again</button></div>}
    </div></section>
    <section className="method" id="method"><span className="section-kicker">THE CORTEX LEARNING ENGINE</span><div className="method-heading"><h2>Not hidden reasoning.<br/><span>Inspectable change.</span></h2><p>A weighted cognitive graph turns experiences into episodic traces, co-activated ideas into connections, and recurring patterns into revisable beliefs.</p></div><div className="method-grid">{[["01","Encode","Extract concepts, emotion, causality, salience, and uncertainty."],["02","Associate","Strengthen co-activated links with salience-weighted updates."],["03","Consolidate","Compress recurring pathways while preserving contradictions."],["04","Compare","Measure graph, belief, response, and decision divergence."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className="formula"><span>CONNECTION UPDATE</span><code>wᵢⱼ(t+1) = λwᵢⱼ(t) + η · activationᵢ · activationⱼ · salience</code><small>A deterministic graph simulation in this prototype; designed for future LLM experience encoding.</small></div></section>
    <section className="impact-section" id="impact"><div className="impact-orbit"><div className="orbit-core">Δ<span>belief change</span></div></div><div className="impact-copy"><span>AI FOR EDUCATION + RESPONSIBLE AI</span><h2>See how a mind<br/>became itself.</h2><p>MindAssembly helps students explore how experience shapes belief and gives AI builders a transparent way to audit personalization. Every change carries provenance: what happened, which links changed, and why a decision followed.</p><div className="use-cases"><span>◈ AI literacy</span><span>◈ Bias simulation</span><span>◈ Explainable personalization</span></div><a className="primary-button" href="#experiment">Fork CORTEX-01 <span>→</span></a></div></section>
    <footer><div className="brand"><span className="brand-mark"><i/><i/><i/><i/></span><span>Mind<span className="brand-light">Assembly</span></span></div><p>BUILD A MIND. CHANGE A LIFE. TRACE THE DIFFERENCE.</p><span>ML EMPOWERMENT BUILD CHALLENGE 2.0 · 2026</span></footer>
  </main>
}
